// <auto-generated />
using System;
using Brasil_Burger_Client.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Brasil_Burger_Client.Migrations
{
    [DbContext(typeof(BrasilBurgerDbContext))]
    [Migration("20251217123411_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Brasil Burger Client.Models.Burger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archive")
                        .HasColumnType("boolean")
                        .HasColumnName("archive");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("prix");

                    b.HasKey("Id");

                    b.ToTable("burgers", (string)null);
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_commande");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("etat");

                    b.Property<int?>("LivreurId")
                        .HasColumnType("integer")
                        .HasColumnName("livreur_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DateCommande");

                    b.HasIndex("Etat");

                    b.HasIndex("LivreurId");

                    b.HasIndex("ZoneId");

                    b.ToTable("commandes", (string)null);
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Complement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archive")
                        .HasColumnType("boolean")
                        .HasColumnName("archive");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("prix");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("complements", (string)null);
                });

            modelBuilder.Entity("Brasil Burger Client.Models.LigneCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BurgerId")
                        .HasColumnType("integer")
                        .HasColumnName("burger_id");

                    b.Property<int>("CommandeId")
                        .HasColumnType("integer")
                        .HasColumnName("commande_id");

                    b.Property<int?>("ComplementId")
                        .HasColumnType("integer")
                        .HasColumnName("complement_id");

                    b.Property<int?>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("prix_unitaire");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.HasKey("Id");

                    b.HasIndex("BurgerId");

                    b.HasIndex("CommandeId");

                    b.HasIndex("ComplementId");

                    b.HasIndex("MenuId");

                    b.ToTable("lignes_commande", (string)null);
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Livreur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.HasKey("Id");

                    b.ToTable("livreurs", (string)null);
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archive")
                        .HasColumnType("boolean")
                        .HasColumnName("archive");

                    b.Property<int>("BoissonId")
                        .HasColumnType("integer")
                        .HasColumnName("boisson_id");

                    b.Property<int>("BurgerId")
                        .HasColumnType("integer")
                        .HasColumnName("burger_id");

                    b.Property<int>("FriteId")
                        .HasColumnType("integer")
                        .HasColumnName("frite_id");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.HasIndex("BoissonId");

                    b.HasIndex("BurgerId");

                    b.HasIndex("FriteId");

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeId")
                        .HasColumnType("integer")
                        .HasColumnName("commande_id");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_paiement");

                    b.Property<string>("Methode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("methode");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("montant");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId")
                        .IsUnique();

                    b.ToTable("paiements", (string)null);
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("prix");

                    b.Property<string>("Quartiers")
                        .HasColumnType("text")
                        .HasColumnName("quartiers");

                    b.HasKey("Id");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Commande", b =>
                {
                    b.HasOne("Brasil Burger Client.Models.Client", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Brasil Burger Client.Models.Livreur", "Livreur")
                        .WithMany("Commandes")
                        .HasForeignKey("LivreurId");

                    b.HasOne("Brasil Burger Client.Models.Zone", "Zone")
                        .WithMany("Commandes")
                        .HasForeignKey("ZoneId");

                    b.Navigation("Client");

                    b.Navigation("Livreur");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Brasil Burger Client.Models.LigneCommande", b =>
                {
                    b.HasOne("Brasil Burger Client.Models.Burger", "Burger")
                        .WithMany("LignesCommande")
                        .HasForeignKey("BurgerId");

                    b.HasOne("Brasil Burger Client.Models.Commande", "Commande")
                        .WithMany("Lignes")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Brasil Burger Client.Models.Complement", "Complement")
                        .WithMany("LignesCommande")
                        .HasForeignKey("ComplementId");

                    b.HasOne("Brasil Burger Client.Models.Menu", "Menu")
                        .WithMany("LignesCommande")
                        .HasForeignKey("MenuId");

                    b.Navigation("Burger");

                    b.Navigation("Commande");

                    b.Navigation("Complement");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Menu", b =>
                {
                    b.HasOne("Brasil Burger Client.Models.Complement", "Boisson")
                        .WithMany("MenusBoisson")
                        .HasForeignKey("BoissonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Brasil Burger Client.Models.Burger", "Burger")
                        .WithMany()
                        .HasForeignKey("BurgerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Brasil Burger Client.Models.Complement", "Frite")
                        .WithMany("MenusFrite")
                        .HasForeignKey("FriteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boisson");

                    b.Navigation("Burger");

                    b.Navigation("Frite");
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Paiement", b =>
                {
                    b.HasOne("Brasil Burger Client.Models.Commande", "Commande")
                        .WithOne("Paiement")
                        .HasForeignKey("Brasil Burger Client.Models.Paiement", "CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Burger", b =>
                {
                    b.Navigation("LignesCommande");
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Client", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Commande", b =>
                {
                    b.Navigation("Lignes");

                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Complement", b =>
                {
                    b.Navigation("LignesCommande");

                    b.Navigation("MenusBoisson");

                    b.Navigation("MenusFrite");
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Livreur", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Menu", b =>
                {
                    b.Navigation("LignesCommande");
                });

            modelBuilder.Entity("Brasil Burger Client.Models.Zone", b =>
                {
                    b.Navigation("Commandes");
                });
#pragma warning restore 612, 618
        }
    }
}
